Opened: /afs/cern.ch/work/i/idutta/private/HCAL_muALCA/CMSSW_10_1_6/src/Muon_Calibration_noTrack_2018/muon_calibration_ana/bash/condor/condor_submit/runList_SingleMuonGun_NoPU_ieta27_Oct20_72.txt
Added file: /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_423.root
Added file: /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_424.root
Added file: /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_425.root
Added file: /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_426.root
Added file: /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_427.root
SysError in <TFile::TFile>: file /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/ntuples/20Oct2018/HCALSampleSingleMuonGun_NoPU_ieta27_Oct20/20Oct2018SingleMuonGun_NoPU_ieta27_Oct20_job72_nvtx_sel-1.root can not be opened (Transport endpoint is not connected)
Error in <TFile::TFile>: file /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_423.root does not exist
Error in <TFile::TFile>: file /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_424.root does not exist
Error in <TFile::TFile>: file /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_425.root does not exist
Error in <TFile::TFile>: file /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_426.root does not exist
Error in <TFile::TFile>: file /eos/cms/store/group/dpg_hcal/comm_hcal/idutta/SingleMuonPt_20GeV_eta_0_3/SingleMuonGun_NoPU_ieta27_Oct20/181021_192040/0000/Validation_427.root does not exist

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00002b7858c5517c in waitpid () from /lib64/libc.so.6
#1  0x00002b7858bd2e52 in do_system () from /lib64/libc.so.6
#2  0x00002b7857237568 in TUnixSystem::StackTrace() () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_6/external/slc6_amd64_gcc630/lib/libCore.so
#3  0x00002b7857239a1c in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_1_6/external/slc6_amd64_gcc630/lib/libCore.so
#4  <signal handler called>
#5  0x000000000040d0d0 in NtuplerReader::Loop (this=0x39288d0, path=<incomplete type>, prefix=<incomplete type>, nvtx_sel=-1) at NtuplerReader.C:239
#6  0x0000000000405405 in main (argc=5, argv=0x7ffe1350e648) at readMC.C:32
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x000000000040d0d0 in NtuplerReader::Loop (this=0x39288d0, path=<incomplete type>, prefix=<incomplete type>, nvtx_sel=-1) at NtuplerReader.C:239
#6  0x0000000000405405 in main (argc=5, argv=0x7ffe1350e648) at readMC.C:32
===========================================================


